import { Aluno } from "./Aluno.js";
import { Bolsista } from "./Bolsista.js";
import { Visitante } from "./Visitante.js";
const p1 = new Visitante();
p1.setNome("Gabriel");
p1.setIdade(26);
p1.setSexo("masculino");
p1.mostrarDados();
console.log("-".repeat(50));
const p2 = new Aluno();
p2.setNome("Cláudia");
p2.setIdade(29);
p2.setSexo("Feminino");
p2.setCurso("Direito");
p2.setMat(12858);
p2.mostrarDados();
p2.pagarMensal();
console.log("-".repeat(50));
const p3 = new Bolsista();
p3.setNome("Luiz");
p3.setIdade(28);
p3.setSexo("masculino");
p3.setMat(127912);
p3.setBolsa(6000);
p3.setCurso("Ciência da Computação");
p3.mostrarDados();
p3.fazerAniversario();
p3.pagarMensal();
p3.renovarBolsa();
